### ISSUE TITLE
New canary update may have broken it?

### ISSUE THREAD

**Issue by SheepCommander** [12944qwerty/report-messages#5]
![image](https://user-images.githubusercontent.com/66646514/148933714-5da91283-8659-4602-8f68-8434619d2372.png)

**Comment by 12944qwerty** [comment]
![image](https://user-images.githubusercontent.com/45984786/149001827-b8f160c1-0c69-4d8e-b624-e151816a5355.png)
works for me
I updated everything to full and just remounted report messages.

Make sure it's enabled I guess? I'm not sure

**Comment by SheepCommander** [comment]
@12944qwerty I kinda figured something out! It allows me to report messages in certain servers and dms, but not all servers or dms... uh oh just now noticed for the first time that some of the `pc-` plugins are missing like moduleManager.

I'll report back after unplugging and replugging

**Comment by SheepCommander** [comment]
Works!
